### ISSUE TITLE
Evaluate `is_valid_signature` Implementation

### ISSUE THREAD

**Issue by neotheprogramist** [cartridge-gg/cairo-webauthn#18]
## Description
The method `is_valid_signature` contains a TODO that needs to be addressed. 

## Details
- **Location 1:** [SessionKey.cairo#L118-L122](https://github.com/argentlabs/starknet-plugin-account/blob/3c14770c3f7734ef208536d91bbd76af56dc2043/contracts/plugins/SessionKey.cairo#L118-L122)
- **Location 2:** [SessionKey.cairo#L36-L37](https://github.com/argentlabs/starknet-plugin-account/blob/3c14770c3f7734ef208536d91bbd76af56dc2043/contracts/plugins/SessionKey.cairo#L36-L37)

## Required Action
- Clarify the intended behavior and purpose of the `is_valid_signature` method.
- Determine if the implementation should be within this method or relocated elsewhere.

**Comment by ThePinion** [comment]
This mechanism was implemented when combining the session logic with a contract (https://github.com/cartridge-gg/cairo-webauthn/pull/33 and https://github.com/cartridge-gg/cairo-webauthn/pull/34)
