### ISSUE TITLE
Proptests execution time

### ISSUE THREAD

**Issue by piniom** [cartridge-gg/cairo-webauthn#58]
We are using a [proptest](https://crates.io/crates/proptest) crate to run some of the tests. The default number of required positive runs for each test is 256. This can be changed using an environment variable. 
Due to the kind of data we are operating on (large numbers and structures derived from these large numbers) the running time is very long. On CI it's over [30 minutes](https://github.com/cartridge-gg/cairo-webauthn/actions/runs/8630657204/job/23657393410). 
![Screenshot from 2024-04-10 15-11-16](https://github.com/cartridge-gg/cairo-webauthn/assets/58044978/0715bf43-f440-42dc-bc0c-05557797ca80)

I think on CI we should lower the number from 256 to something like 8 or 16. 
If we don't want to compromise the testing precision on the main branch we could at leas differentiate between PRs and the main branch.
There is also a possibility to optimise the tests but I don't know to what extent and how hard it is. Lowering the number is definitely the easiest approach
What do you think @neotheprogramist @glihm @broody?

**Comment by neotheprogramist** [comment]
@piniom 
I think we can safely lower the number of tests for now, and if we optimize the code we could gradually enlarge it
